export const DOCUMENT_HISTORY_RETENTION_LIMIT = 100;
export const DOCUMENT_HISTORY_LIST_LIMIT = 50;
export const DOCUMENT_HISTORY_PATCH_THRESHOLD = 0.7;
export const DOCUMENT_HISTORY_SNAPSHOT_INTERVAL = 10;

export const FREE_DOCUMENT_HISTORY_WINDOW_DAYS = 30;
